/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package daftarfilm;

import java.awt.GridLayout;

/**
 *
 * @author Fachri
 */
public class FrameMenu extends javax.swing.JFrame{
    private String flag;
    private String name;
    private boolean isUpdated;
    /**
     * Creates new form JPanelCard
     */
    public FrameMenu(String name) {
        initComponents();
        this.name = name;
        this.flag = "film";
        setPanelFilm();
        this.isUpdated = true;
    }
    public String getFlag() {
      return flag;
    }
    public void setFlag(String flag) {
      this.flag = flag;
    }
    public void setIsUpdated(boolean isUpdated) {
      this.isUpdated = isUpdated;
    }
    public boolean getIsUpdated() {
      return isUpdated;
    }
    
    public void onDataUpdated() {
        // Refresh data in Frame1 here
        if(this.flag.equals("film")){
            setPanelFilm();
        }else{
            setPanelArtis();
        }
    }
    
    
    public void setPanelFilm() {
        mainPanel.removeAll();
        mainPanel.setLayout(new GridLayout(0, 1));
        mainPanel.add(new MenuFilm(this));
        mainPanel.revalidate();
        mainPanel.repaint();
        setFlag("film");
    }
    public void setPanelArtis() {
        mainPanel.removeAll();
        mainPanel.setLayout(new GridLayout(0, 1));
        mainPanel.add(new MenuArtis(this));
        mainPanel.revalidate();
        mainPanel.repaint();
        setFlag("artis");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        ButtonArtis = new javax.swing.JButton();
        ButtonFilm = new javax.swing.JButton();
        ButtonAdd = new javax.swing.JButton();
        ButtonRelasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainPanel);

        ButtonArtis.setText("Artis");
        ButtonArtis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonArtisActionPerformed(evt);
            }
        });

        ButtonFilm.setText("Film");
        ButtonFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFilmActionPerformed(evt);
            }
        });

        ButtonAdd.setText("Add");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });

        ButtonRelasi.setText("X");
        ButtonRelasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRelasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(ButtonFilm)
                .addGap(18, 18, 18)
                .addComponent(ButtonRelasi)
                .addGap(18, 18, 18)
                .addComponent(ButtonArtis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonAdd)
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonArtis)
                    .addComponent(ButtonFilm)
                    .addComponent(ButtonAdd)
                    .addComponent(ButtonRelasi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFilmActionPerformed
        setPanelFilm();        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonFilmActionPerformed

    private void ButtonArtisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonArtisActionPerformed
        // TODO add your handling code here:
        setPanelArtis();
    }//GEN-LAST:event_ButtonArtisActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        // TODO add your handling code here:
        this.setIsUpdated(false);
        if(this.flag.equals("film")){
            FrameAddFilm frame = new FrameAddFilm(this);
            frame.setSize(400, 300);
            frame.setDefaultCloseOperation(FrameAddFilm.DISPOSE_ON_CLOSE);

            frame.setVisible(true);
        }else{
            FrameAddArtis frame = new FrameAddArtis(this);
            frame.setSize(400, 300);
            frame.setDefaultCloseOperation(FrameAddArtis.DISPOSE_ON_CLOSE);
            
            frame.setVisible(true);
        }
        
        
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void ButtonRelasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRelasiActionPerformed
        // TODO add your handling code here:
        FrameArtisFilm frame = new FrameArtisFilm();
        frame.setSize(400, 300);
        frame.setDefaultCloseOperation(FrameArtisFilm.DISPOSE_ON_CLOSE);
        
        frame.setVisible(true);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                
            }
        });
    }//GEN-LAST:event_ButtonRelasiActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonArtis;
    private javax.swing.JButton ButtonFilm;
    private javax.swing.JButton ButtonRelasi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
